#Site settings
title: soijen
email: info@soijen.com
description: At Sóijen we are outdoor adventurers who connect fellow explorers to untapped regions of Patagonia.
lang: ["en", "es"]
url: "https://soijen.com"
twitter_username: soijen_
google_analytics_key: UA-110515448-1
google_site_verification:  EEQMidAdFg7D-e5XOsBLr9_yrpphwc6Yt7Oy0HUMq7g
google_maps_api_key: AIzaSyDA1P82F6tKVJNiiP-tI9dOFrzPcfzX4eE
permalink: /:title/

# Build settings
include: ["_pages"]

#old website redirects
collections:
  redirects:
    output: true
  region:
    output: true

defaults:
  #languages
  -
    scope:
      path: "en"
    values:
      lang: "en"
      baseurl: ""
  -
    scope:
      path: "es"
    values:
      lang: "es"
      baseurl: "/es/"
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
#menu translations
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    contact:
      name: "Contact"
      url: "/contact/"
  es:
      home:
        name: "Inicio"
        url: "/es/"
      about:
        name: "Sobre Nosotros"
        url: "/es/about/"
      contact:
        name: "Contacto"
        url: "/es/contact/"

#prose.io settings
prose:
  rooturl: ''
  siteurl: 'https://edonoso.com'
  media: '/assets/images'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - .gitignore
    - robots.txt
    - sitemap.xml
    - CNAME
  metadata:
    "":
      - name: "title"
        field:
          label: "Title"
          element: "text"
          placeholder: "Add post title here"
      - name: "description"
        field:
          label: "Description"
          element: "text"
          placeholder: "Add post description here"
      - name: "author"
        field:
          element: "hidden"
          value: "Sóijen"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "latitude"
        field:
          label: "latitude"
          element: "text"
          placeholder: "-54.9402407"
      - name: "longitude"
        field:
          label: "longitude"
          element: "text"
          placeholder: "-54.9402407"
      - name: "permalink"
        field:
          label: "Permalink"
          element: "text"
          placeholder: "/la-mauricie-canoe-camping/"
      - name: "postHero"
        field:
          label: "PostHero Link"
          element: "text"
          placeholder: "/assets/images/myphoto.jpg"
      - name: "ref"
        field:
          label: "Language Ref"
          element: "text"
          placeholder: "la-mauricie-canoe-camping"
      - name: "region"
        field:
          label: "region"
          element: "text"
          placeholder: "Choose region"
          options:
            - name: Puerto-Natales
              value: Puerto-Natales
            - name: Punta-Arenas
              value: Punta-Arenas
            - name: Puerto-Williams
              value: Puerto-Williams
            - name: Tierra-del-Fuego
              value: Tierra-del-Fuego
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "sustainability"
              value: "sustainability"
            - name: "bike"
              value: "bike"
            - name: "camping"
              value: "camping"
            - name: "culture"
              value: "culture"
            - name: "trekking"
              value: "trekking"
            - name: "van-life"
              value: "van-life"
            - name: "trail-running"
              value: "trail-running"
      - name: "zoom"
        field:
          label: "zoom"
          element: "text"
          placeholder: "6"
      - name: "date"
        field:
          label: "date"
          element: "text"
          value: "CURRENT_DATETIME"
