# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: sóijen | patagonia [un]explored
email: info@soijen.com
description:
  en: At Sóijen we are outdoor adventurers who connect fellow explorers to untapped regions of Patagonia.
  es: En Sóijen somos aventureros de actividades al aire libre, quienes conectamos otros exploradores con la regiones inexploradas de la Patagonia.
lang: ["Eng", "Esp"]
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://soijen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: soijen_
permalink: /:title/

# Build settings
markdown: kramdown

include: ["_pages"]

defaults:
  #languages
  -
    scope:
      path: "en"
    values:
      lang: "eng"
      baseurl: ""
  -
    scope:
      path: "es"
    values:
      lang: "esp"
      baseurl: "/es/"

#menu translations
t:
  eng:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    contact:
      name: "Contact"
      url: "/contact/"
  esp:
      home:
        name: "Inicio"
        url: "/es/"
      about:
        name: "Sobre Nosotros"
        url: "/es/about/"
      contact:
        name: "Contacto"
        url: "/es/contact/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
