title: sóijen | patagonia [un]explored
email: info@soijen.com
description: At Sóijen we are outdoor adventurers who connect fellow explorers to untapped regions of Patagonia.
lang: ["en", "es"]
url: "https://soijen.com"
twitter_username: soijen_
permalink: /:title/
google_maps_api_key: AIzaSyDA1P82F6tKVJNiiP-tI9dOFrzPcfzX4eE

# Build settings
include: ["_pages"]

#old website redirects
collections:
  redirects:
    output: true
  region:
    output: true

defaults:
  #languages
  -
    scope:
      path: "en"
    values:
      lang: "en"
      baseurl: ""
  -
    scope:
      path: "es"
    values:
      lang: "es"
      baseurl: "/es/"
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
#menu translations
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    contact:
      name: "Contact"
      url: "/contact/"
  es:
      home:
        name: "Inicio"
        url: "/es/"
      about:
        name: "Sobre Nosotros"
        url: "/es/about/"
      contact:
        name: "Contacto"
        url: "/es/contact/"
