#Site settings
title: Soijen
email: info@soijen.com
description:
  en: At Sóijen we create outdoor inspired designs to get you excited for your next adventure, from Patagonia to New England and beyond.
  es: En Sóijen creamos diseños inspirados por el aire libre para motivarte en tu próxima aventura - desde la Patagonia a New England y más allá..
index:
  en:
  es: /es/
feed:
  en: /feed.xml
  es: /es/feed.xml
lang: ["en", "es"]
url: "https://soijen.com"
etsy_username: Soijen
instagram_username: soijen_
facebook_username: soijen
twitter_username: soijen_
youtube_username: UC_9UZ_vZjIx3mfZ1P6r9w6g
google_analytics_key: UA-110515448-1
google_site_verification:  EEQMidAdFg7D-e5XOsBLr9_yrpphwc6Yt7Oy0HUMq7g
#snipcart_api_key: MzNhYjliYWEtOTQ3ZC00ZWFlLThjYWUtYzcyNjYyYjc2OThhNjM2NzkxMTY4MTIyMTIzMzYw
permalink: /:title/

# Build settings
include: ["_pages"]
exclude:
  - node_modules
keep_files: [images]

collections:
  redirects: #old website redirects
    output: true
  region:
    output: true
  products:
    output: true
  portfolio:
    output: true

defaults:
  #languages
  -
    scope:
      path: "en"
    values:
      lang: "en"
      baseurl: ""
  -
    scope:
      path: "es"
    values:
      lang: "es"
      baseurl: "/es/"
  -
    scope:
      path: "_products/en"
    values:
      lang: "en"
      layout: productdetails
      permalink: "/products/:title"
  -
    scope:
      path: "_products/es"
    values:
      lang: "es"
      layout: productdetails
      permalink: "/es/products/:title"
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
  -
    scope:
      path: "_portfolio/en"
    values:
      lang: "en"
      layout: default
  -
    scope:
      path: "_portfolio/es"
    values:
      lang: "es"
      layout: default
  -
    scope:
      path: "es/_posts"
    values:
      layout: post
      author: Sóijen
      featured: 0
  -
    scope:
      path: "en/_posts"
    values:
      layout: post
      author: Sóijen
      featured: 0
